-- ============================================================
-- SEED: Merged BM module questions per level.
-- ============================================================

-- ==========================================================
-- TAHUN 1 (Ilyas): Tatabahasa, Karangan
-- ==========================================================

-- Topic 1: Tatabahasa
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('t1', 1, 'Tatabahasa', '___ itu sangat garang.', 'mcq', array['Kucing', 'Ali', 'Beliau', 'Mereka'], 'Kucing', 'Kucing ialah kata nama am yang sesuai untuk haiwan.', 'easy', array['tatabahasa', 'kata_nama']),
('t1', 1, 'Tatabahasa', 'Nama kucing saya ialah ___.', 'mcq', array['si comel', 'Si Comel', 'kawan', 'budak'], 'Si Comel', 'Si Comel ialah kata nama khas untuk haiwan dan mesti ditulis dengan huruf besar.', 'easy', array['tatabahasa', 'kata_nama']),
('t1', 1, 'Tatabahasa', 'Ali sedang ___ nasi di dapur.', 'mcq', array['makan', 'membaca', 'berlari', 'tidur'], 'makan', 'Makan ialah kata kerja yang merujuk kepada perbuatan memasukkan makanan ke dalam mulut.', 'easy', array['tatabahasa', 'kata_kerja']),
('t1', 1, 'Tatabahasa', 'Ejaan yang betul bagi perkataan ''buku'' ialah ___.', 'mcq', array['b-u-k-u', 'b-u-k', 'b-a-k-u', 'b-o-k-o'], 'b-u-k-u', 'Suku kata bagi buku ialah bu-ku (b-u-k-u).', 'easy', array['tatabahasa', 'suku_kata']),
('t1', 1, 'Tatabahasa', 'Rumah Datuk sangat ___ kerana baru dicat.', 'mcq', array['cantik', 'bising', 'pedas', 'wangi'], 'cantik', 'Cantik ialah kata adjektif pancaindera pandang yang sesuai untuk keadaan rumah.', 'standard', array['tatabahasa', 'kata_adjektif']),
('t1', 1, 'Tatabahasa', 'Cikgu Aminah mengajar di Sekolah Kebangsaan ___.', 'mcq', array['Melati', 'melati', 'budak', 'guru'], 'Melati', 'Melati ialah kata nama khas bagi nama sekolah dan dieja dengan huruf besar.', 'standard', array['tatabahasa', 'kata_nama']),
('t1', 1, 'Tatabahasa', 'Ibu ___ baju adik yang kotor.', 'mcq', array['membasuh', 'memasak', 'melukis', 'memanjat'], 'membasuh', 'Membasuh ialah kata kerja perbuatan membersihkan pakaian menggunakan air.', 'standard', array['tatabahasa', 'kata_kerja']),
('t1', 1, 'Tatabahasa', 'Abu ___ Ali pergi ke perpustakaan bersama-sama.', 'mcq', array['dan', 'atau', 'tetapi', 'sambil'], 'dan', 'Kata hubung ''dan'' digunakan untuk menggabungkan dua subjek yang melakukan aktiviti yang sama.', 'standard', array['tatabahasa', 'kata_hubung']),
('t1', 1, 'Tatabahasa', 'Pilih ayat yang menggunakan Kata Nama Khas dengan betul.', 'mcq', array['Kami melawat Zoo Negara pada hari Ahad.', 'Kami melawat zoo negara pada hari ahad.', 'Kami melawat Zoo negara pada hari Ahad.', 'Kami melawat zoo Negara pada Hari Ahad.'], 'Kami melawat Zoo Negara pada hari Ahad.', 'Zoo Negara dan Ahad merupakan Kata Nama Khas yang wajib ditulis dengan huruf besar pada setiap huruf pertama perkataan.', 'kbat', array['tatabahasa', 'kata_nama']),
('t1', 1, 'Tatabahasa', 'Adik ___ kerana terjatuh dari basikal dan kakinya sakit.', 'mcq', array['menangis', 'ketawa', 'melompat', 'menyanyi'], 'menangis', 'Menangis ialah respon semula jadi apabila mengalami kesakitan fizikal.', 'kbat', array['tatabahasa', 'kata_kerja']),
('t1', 1, 'Tatabahasa', '''Sekolah'' ialah Kata Nama Khas.', 'true_false', array['Betul', 'Salah'], 'Salah', '''Sekolah'' ialah kata nama am. Contoh kata nama khas ialah Sekolah Kebangsaan Taman Melati.', 'easy', array['tatabahasa', 'kata_nama']),
('t1', 1, 'Tatabahasa', 'Perkataan ''meja'' mempunyai dua suku kata.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Perkataan ''meja'' dieja me-ja (2 suku kata).', 'easy', array['tatabahasa', 'suku_kata']),
('t1', 1, 'Tatabahasa', '''Proton Saga'' ialah Kata Nama Khas bagi benda yang ditulis dengan huruf besar.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Nama jenama kereta seperti Proton Saga merupakan kata nama khas.', 'standard', array['tatabahasa', 'kata_nama']),
('t1', 1, 'Tatabahasa', 'Perkataan ''membaca'' ialah kata kerja.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Membaca ialah kata kerja kerana ia menunjukkan suatu perbuatan yang dilakukan oleh manusia.', 'standard', array['tatabahasa', 'kata_kerja']),
('t1', 1, 'Tatabahasa', 'Dalam ayat ''Buah betik itu sangat manis'', perkataan ''manis'' ialah kata kerja.', 'true_false', array['Betul', 'Salah'], 'Salah', 'Perkataan ''manis'' menerangkan sifat/rasa buah betik tersebut, maka ia merupakan kata adjektif.', 'kbat', array['tatabahasa', 'kata_adjektif']),
('t1', 1, 'Tatabahasa', '___ itu sedang terbang tinggi di langit.', 'fill_blank', null, 'Burung', 'Burung ialah haiwan yang mempunyai kepak dan boleh terbang.', 'easy', array['tatabahasa', 'kata_nama']),
('t1', 1, 'Tatabahasa', 'Bapa sedang ___ surat khabar di ruang tamu.', 'fill_blank', null, 'membaca', 'Kata kerja membaca paling sesuai digunakan untuk bahan bacaan seperti surat khabar.', 'easy', array['tatabahasa', 'kata_kerja']),
('t1', 1, 'Tatabahasa', 'Pisau itu sangat ___ kerana baru diasah oleh bapa.', 'fill_blank', null, 'tajam', 'Tajam ialah sifat bagi alat pemotong yang boleh memotong objek dengan mudah.', 'standard', array['tatabahasa', 'kata_adjektif']),
('t1', 1, 'Tatabahasa', 'Lengkapkan perkataan ''kereta'' dengan suku kata yang betul: ke - ___ - ta.', 'fill_blank', null, 're', 'Ejaan lengkap bagi kereta ialah ke-re-ta.', 'standard', array['tatabahasa', 'suku_kata']),
('t1', 1, 'Tatabahasa', 'Siti membela seekor kucing kesayangan yang dinamakan ___ Comel.', 'fill_blank', null, 'Si', 'Kata sandang ''Si'' digunakan sebelum kata nama khas bagi merujuk kepada haiwan.', 'kbat', array['tatabahasa', 'kata_nama']);

-- Topic 2: Karangan
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('t1', 2, 'Karangan', 'Susun perkataan-perkataan berikut supaya menjadi ayat yang betul: [bola] [Ali] [main]', 'mcq', array['Ali main bola.', 'Bola Ali main.', 'Main Ali bola.', 'Ali bola main.'], 'Ali main bola.', 'Struktur ayat tunggal bermula dengan subjek (Ali) diikuti kata kerja (main) dan objek (bola).', 'easy', array['karangan', 'susun_perkataan', 'ayat_mudah']),
('t1', 2, 'Karangan', 'Kakak sedang menyapu ___ di ruang tamu.', 'mcq', array['sampah', 'air', 'nasi', 'baju'], 'sampah', 'Kata kerja menyapu biasanya berpasangan dengan objek sampah di lantai.', 'easy', array['karangan', 'lengkapkan_ayat']),
('t1', 2, 'Karangan', 'Pilih ayat yang mempunyai susunan tatabahasa yang betul.', 'mcq', array['Saya suka makan oren buah.', 'Saya suka makan buah oren.', 'Suka saya makan buah oren.', 'Makan saya suka buah oren.'], 'Saya suka makan buah oren.', 'Frasa nama yang betul ialah buah oren (bukan oren buah, mengikut hukum D-M).', 'easy', array['karangan', 'ayat_mudah']),
('t1', 2, 'Karangan', 'Susun perkataan berikut menjadi ayat yang betul: [buku] [baca] [Ibu]', 'mcq', array['Ibu baca buku.', 'Buku baca ibu.', 'Baca ibu buku.', 'Ibu buku baca.'], 'Ibu baca buku.', 'Susunan betul ialah Subjek + Kata Kerja + Objek.', 'easy', array['karangan', 'susun_perkataan', 'ayat_mudah']),
('t1', 2, 'Karangan', 'Pilih gabungan ayat yang betul bagi: ''Adik menangis.'' dan ''Adik lapar susu.''', 'mcq', array['Adik menangis kerana lapar susu.', 'Adik menangis tetapi lapar susu.', 'Adik menangis lalu lapar susu.', 'Adik menangis dan lapar susu.'], 'Adik menangis kerana lapar susu.', 'Kata hubung ''kerana'' digunakan untuk menyatakan sebab atau alasan adik menangis.', 'standard', array['karangan', 'kata_hubung', 'ayat_mudah']),
('t1', 2, 'Karangan', 'Lengkapkan huraian tentang kucing: ''Ini kucing saya. Bulunya ___.''', 'mcq', array['tebal dan lembut', 'keras dan kasar', 'pahit dan manis', 'wangi dan bising'], 'tebal dan lembut', 'Sifat fizikal bulu kucing yang sihat biasanya tebal dan lembut.', 'standard', array['karangan', 'lengkapkan_ayat']),
('t1', 2, 'Karangan', 'Susun perkataan-perkataan berikut: [ke] [Amin] [sekolah] [pergi] [basikal] [menunggang]', 'mcq', array['Amin pergi ke sekolah menunggang basikal.', 'Amin menunggang basikal pergi ke sekolah.', 'Amin pergi menunggang ke sekolah basikal.', 'Basikal Amin menunggang pergi ke sekolah.'], 'Amin menunggang basikal pergi ke sekolah.', 'Susunan ayat bermaksud Amin bergerak ke sekolah dengan menunggang basikal.', 'standard', array['karangan', 'susun_perkataan']),
('t1', 2, 'Karangan', 'Pilih ayat dengan tanda baca yang betul untuk menyatakan perasaan kagum.', 'mcq', array['Wah, cantiknya baju kamu!', 'Wah cantiknya baju kamu.', 'wah, cantiknya baju kamu?', 'Wah! cantiknya baju kamu.'], 'Wah, cantiknya baju kamu!', 'Ayat seruan bermula dengan kata seru (Wah), diikuti koma (,), dan diakhiri tanda seru (!).', 'standard', array['karangan', 'tanda_baca']),
('t1', 2, 'Karangan', 'Setiap pagi, kami sekeluarga ___ sarapan bersama-sama.', 'mcq', array['makan', 'memasak', 'membeli', 'bersiap'], 'makan', 'Kata kerja makan paling sesuai dengan perkataan sarapan.', 'standard', array['karangan', 'lengkapkan_ayat']),
('t1', 2, 'Karangan', 'Pilih perenggan yang paling tersusun untuk menceritakan tentang ''Kucing Saya''.', 'mcq', array['Saya ada seekor kucing. Namanya Si Belang. Bulunya sangat cantik. Saya sayang akan Si Belang.', 'Kucing saya suka makan nasi. Si Belang nama dia. Saya sayang dia sangat.', 'Belang saya sayang kucing. Bulunya cantik nama Si Belang.', 'Ini kucing belang. Sangat saya sayang dia.'], 'Saya ada seekor kucing. Namanya Si Belang. Bulunya sangat cantik. Saya sayang akan Si Belang.', 'Perenggan ini mempunyai susunan ayat yang koheren, mudah difahami, dan tatabahasa yang tepat.', 'kbat', array['karangan', 'bina_perenggan']),
('t1', 2, 'Karangan', 'Lengkapkan cerita pendek berikut: ''Hari ini hari lahir saya. Ibu ___ kek coklat. Kami ___ bersama-sama.''', 'mcq', array['membuat, makan', 'membuang, lari', 'membaca, tidur', 'membeli, bermain'], 'membuat, makan', 'Kombinasi kata kerja membuat kek dan memakannya sesuai dengan konteks sambutan hari lahir.', 'kbat', array['karangan', 'lengkapkan_ayat']),
('t1', 2, 'Karangan', 'Susun perkataan berikut supaya menjadi ayat yang gramatis: [pokok] [tumbuh] [tepi] [itu] [di] [sungai]', 'mcq', array['Pokok itu tumbuh di tepi sungai.', 'Tumbuh sungai di tepi pokok itu.', 'Di tepi pokok itu tumbuh sungai.', 'Sungai itu tumbuh di tepi pokok.'], 'Pokok itu tumbuh di tepi sungai.', 'Pokok tumbuh di tepi sungai adalah susunan subjek, predikat dan keterangan tempat yang logik dan betul.', 'kbat', array['karangan', 'susun_perkataan']),
('t1', 2, 'Karangan', 'Susun perkataan berikut dengan betul: [mengemas] [Ahmad] [tidur] [bilik] [bangun] [selepas]', 'mcq', array['Ahmad mengemas bilik tidur selepas bangun.', 'Bilik tidur mengemas Ahmad selepas bangun.', 'Selepas bangun bilik tidur Ahmad mengemas.', 'Ahmad bangun selepas mengemas bilik tidur.'], 'Ahmad mengemas bilik tidur selepas bangun.', 'Ayat bermaksud Ahmad melakukan kerja kemas bilik tidur selepas dia bangun daripada tidur.', 'kbat', array['karangan', 'susun_perkataan']),
('t1', 2, 'Karangan', 'Bunga mawar berwarna merah. Bunga mawar ___ bau.', 'mcq', array['mempunyai harum', 'berbau harum', 'menghidu harum', 'ditiup harum'], 'berbau harum', 'Berbau harum ialah frasa kerja yang menyatakan ciri bauan bagi bunga.', 'kbat', array['karangan', 'lengkapkan_ayat']),
('t1', 2, 'Karangan', 'Susun ayat-ayat berikut supaya menjadi cerita yang lengkap.
I. Ibu mencuci luka itu.
II. Ali terjatuh semasa bermain bola.
III. Ali mengucapkan terima kasih kepada ibu.', 'mcq', array['II, I, III', 'I, II, III', 'III, II, I', 'II, III, I'], 'II, I, III', 'Cerita bermula dengan Ali jatuh (II), disusuli tindakan ibu merawat (I), dan diakhiri ucapan terima kasih (III).', 'kbat', array['karangan', 'susun_ayat']),
('t1', 2, 'Karangan', 'Ayat ''Makan nasi saya'' mempunyai susunan ayat yang betul dalam Bahasa Melayu.', 'true_false', array['Betul', 'Salah'], 'Salah', 'Susunan yang betul dalam ayat tunggal ialah Subjek dahulu baru diikuti Predikat, iaitu ''Saya makan nasi''.', 'easy', array['karangan', 'ayat_mudah']),
('t1', 2, 'Karangan', 'Ayat ''Adik sedang tidur di atas katil'' mempunyai subjek ''Adik sedang''.', 'true_false', array['Betul', 'Salah'], 'Salah', 'Subjek bagi ayat ini ialah ''Adik''. Perkataan ''sedang tidur di atas katil'' merupakan sebahagian daripada predikat.', 'standard', array['karangan', 'ayat_mudah']),
('t1', 2, 'Karangan', 'Ayat ''Siti suka melukis tetapi abangnya suka membaca'' ialah ayat tunggal.', 'true_false', array['Betul', 'Salah'], 'Salah', 'Ayat ini merupakan ayat majmuk kerana menggunakan kata hubung pancangan ''tetapi'' untuk menggabungkan dua klausa.', 'kbat', array['karangan', 'ayat_mudah']),
('t1', 2, 'Karangan', 'Lengkapkan ayat: Kami sekeluarga bekerjasama ___ kawasan rumah pada hujung minggu.', 'fill_blank', null, 'membersihkan', 'Perbuatan bergotong-royong di kawasan rumah merujuk kepada aktiviti membersihkan.', 'standard', array['karangan', 'lengkapkan_ayat']),
('t1', 2, 'Karangan', 'Susun perkataan berikut supaya menjadi ayat lengkap: [kawan] [saya] [Zaki] [ialah] .', 'fill_blank', null, 'Zaki ialah kawan saya', 'Ayat yang lengkap dibina dengan meletakkan pelaku/nama subjek di hadapan diikuti pemeri ''ialah'' dan frasa penerang.', 'kbat', array['karangan', 'susun_perkataan']);

-- ==========================================================
-- TAHUN 4 (Hafeeza): Tatabahasa, Karangan
-- ==========================================================

-- Topic 1: Tatabahasa - Kata Adjektif
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('t4', 1, 'Tatabahasa - Kata Adjektif', 'Pilih kata adjektif pancaindera yang sesuai untuk melengkapkan ayat ini: "Sup ayam yang dimasak oleh ibu berbau sangat __________."', 'mcq', array['A. hanyir', 'B. harum', 'C. kelat', 'D. tengik'], 'B', 'Kata adjektif ''harum'' menerangkan bau yang menyenangkan daripada makanan atau masakan.', 'easy', array['tatabahasa', 'kata_adjektif', 'pancaindera']),
('t4', 1, 'Tatabahasa - Kata Adjektif', 'Tayar kereta mainan yang baru dibeli oleh ayah itu berbentuk __________.', 'mcq', array['A. bulat', 'B. leper', 'C. bujur', 'D. segi tiga'], 'A', 'Tayar kenderaan berbentuk bulat untuk membolehkannya bergerak dengan lancar.', 'easy', array['tatabahasa', 'kata_adjektif', 'sifat_rupa']),
('t4', 1, 'Tatabahasa - Kata Adjektif', 'Antara ayat berikut, yang manakah menggunakan kata adjektif cara dengan betul?', 'mcq', array['A. Aliff memandu keretanya dengan lambat kerana tergesa-gesa.', 'B. Pelari itu berlari dengan pantas untuk memenangi perlumbaan.', 'C. Hujan turun dengan lebat di petang hari.', 'D. Murid itu menulis dengan kemas menggunakan pensel tajam.'], 'B', 'Kata adjektif cara ''pantas'' menerangkan cara pelari itu berlari dengan laju.', 'kbat', array['tatabahasa', 'kata_adjektif', 'cara']),
('t4', 1, 'Tatabahasa - Kata Adjektif', 'Perkataan ''merdu'' ialah kata adjektif pancaindera dengar yang menerangkan tentang bunyi suara atau muzik.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Perkataan ''merdu'' merujuk kepada bunyi yang sedap didengar, seperti suara nyanyian atau gesekan biola.', 'easy', array['tatabahasa', 'kata_adjektif', 'pancaindera']),
('t4', 1, 'Tatabahasa - Kata Adjektif', 'Dalam ayat "Bilik tidur kakak sangat kemas dan bersih", perkataan ''kemas'' dan ''bersih'' merupakan kata adjektif ukuran.', 'true_false', array['Betul', 'Salah'], 'Salah', 'Perkataan ''kemas'' dan ''bersih'' merupakan kata adjektif keadaan, bukannya kata adjektif ukuran.', 'standard', array['tatabahasa', 'kata_adjektif', 'keadaan']),
('t4', 1, 'Tatabahasa - Kata Adjektif', 'Air laut di kawasan Selat Melaka itu kelihatan __________ biru apabila cuaca cerah. (Isi tempat kosong dengan kata penguat yang sesuai)', 'fill_blank', null, 'sangat', 'Kata penguat ''sangat'', ''amat'', atau ''sungguh'' digunakan sebelum kata adjektif warna ''biru'' untuk menunjukkan darjah warna tersebut.', 'easy', array['tatabahasa', 'kata_adjektif', 'kata_penguat']),
('t4', 1, 'Tatabahasa - Kata Adjektif', 'Lengkapkan ayat berikut dengan kata adjektif waktu yang sesuai: "Kita mestilah bangun __________ pagi supaya tidak terlewat ke sekolah."', 'fill_blank', null, 'awal', 'Kata adjektif ''awal'' menunjukkan waktu yang mendahului waktu yang ditetapkan.', 'standard', array['tatabahasa', 'kata_adjektif', 'waktu']);

-- Topic 2: Tatabahasa - Imbuhan
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('t4', 2, 'Tatabahasa - Imbuhan', 'Pilih perkataan yang menggunakan imbuhan awalan dengan betul untuk melengkapkan ayat: "Ahmad sedang __________ buku cerita di perpustakaan."', 'mcq', array['A. dibaca', 'B. membaca', 'C. pembaca', 'D. terbaca'], 'B', 'Imbuhan awalan ''meN-'' (membaca) menunjukkan kata kerja aktif transitif yang sesuai dengan perbuatan Ahmad membaca buku.', 'easy', array['tatabahasa', 'imbuhan', 'awalan']),
('t4', 2, 'Tatabahasa - Imbuhan', '"Seni pertahanan diri itu __________ oleh guru silat yang berpengalaman."', 'mcq', array['A. diajarkan', 'B. belajar', 'C. mengajar', 'D. pelajaran'], 'A', 'Perkataan ''diajarkan'' menggunakan imbuhan apitan ''di-...-kan'' untuk membina ayat pasif yang sesuai dengan konteks ayat.', 'standard', array['tatabahasa', 'imbuhan', 'apitan']),
('t4', 2, 'Tatabahasa - Imbuhan', 'Kenal pasti perkataan berimbuhan apitan dalam ayat ini yang menunjukkan proses atau hasil daripada sesuatu tindakan: "Persatuan Ibu Bapa dan Guru mengadakan perbincangan tentang keselamatan murid."', 'mcq', array['A. keselamatan', 'B. perbincangan', 'C. mengadakan', 'D. persatuan'], 'B', 'Kata nama ''perbincangan'' (daripada kata dasar bincang) bermaksud proses atau hal berbincang.', 'kbat', array['tatabahasa', 'imbuhan', 'apitan', 'kata_nama']),
('t4', 2, 'Tatabahasa - Imbuhan', 'Apakah imbuhan akhiran yang sesuai untuk menukarkan kata dasar ''lukis'' menjadi kata nama yang bermaksud gambar yang dilukis?', 'mcq', array['A. -an (lukisan)', 'B. -kan (lukiskan)', 'C. -i (lukisi)', 'D. -wan (lukiswan)'], 'A', 'Imbuhan akhiran ''-an'' pada kata dasar ''lukis'' menghasilkan kata nama ''lukisan'' yang merujuk kepada hasil seni lukis.', 'easy', array['tatabahasa', 'imbuhan', 'akhiran']),
('t4', 2, 'Tatabahasa - Imbuhan', 'Pilih penggunaan imbuhan apitan yang betul bagi kata dasar ''besar'' untuk mengisi tempat kosong dalam ayat.', 'mcq', array['A. memperbesarkan', 'B. membesarkan', 'C. diperbesarkan', 'D. memperbesar-besarkan'], 'B', 'Kata kerja ''membesarkan'' adalah betul. Kata ''memperbesar'' juga betul tetapi tidak boleh diikuti dengan akhiran ''-kan'' (penggunaan ''memperbesarkan'' adalah salah dari segi tatabahasa).', 'standard', array['tatabahasa', 'imbuhan', 'apitan', 'kesalahan_lazim']),
('t4', 2, 'Tatabahasa - Imbuhan', '"Buku-buku di atas meja itu berselerak." Apakah maksud imbuhan awalan ''ber-'' pada perkataan ''berselerak''?', 'mcq', array['A. mempunyai sesuatu', 'B. dalam keadaan terbiar atau bertaburan', 'C. melakukan perbuatan sendiri', 'D. saling berkaitan antara satu sama lain'], 'B', 'Imbuhan awalan ''ber-'' pada perkataan ''berselerak'' menunjukkan keadaan bertaburan atau bersepah.', 'kbat', array['tatabahasa', 'imbuhan', 'awalan']),
('t4', 2, 'Tatabahasa - Imbuhan', 'Tulis kata berimbuhan yang betul bagi kata dasar ''tulis'' untuk melengkapkan ayat pasif berikut: "Surat kiriman itu __________ oleh abang kelmarin."', 'fill_blank', null, 'ditulis', 'Imbuhan awalan ''di-'' digunakan untuk membentuk kata kerja pasif ''ditulis'' bagi menunjukkan perbuatan yang dilakukan oleh orang ketiga (abang).', 'standard', array['tatabahasa', 'imbuhan', 'awalan', 'kata_kerja_pasif']);

-- Topic 3: Tatabahasa - Ayat Tunggal dan Majmuk
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('t4', 3, 'Tatabahasa - Ayat Tunggal dan Majmuk', 'Antara berikut, yang manakah merupakan contoh ayat tunggal?', 'mcq', array['A. Bapa membaca surat khabar manakala ibu memasak di dapur.', 'B. Aminah menyanyi dengan merdu sekali.', 'C. Haziq tidak pergi ke padang kerana hujan lebat.', 'D. Murid-murid sedang belajar dan guru sedang memerhati.'], 'B', 'Ayat tunggal hanya mengandungi satu subjek (''Aminah'') dan satu predikat (''menyanyi dengan merdu sekali'').', 'easy', array['tatabahasa', 'ayat_tunggal']),
('t4', 3, 'Tatabahasa - Ayat Tunggal dan Majmuk', 'Pilih kata hubung yang paling sesuai untuk menggabungkan dua ayat tunggal berikut: \nAyat 1: "Siti suka melukis." \nAyat 2: "Siti tidak suka mewarna."', 'mcq', array['A. dan', 'B. tetapi', 'C. lalu', 'D. sambil'], 'B', 'Kata hubung pertentangan ''tetapi'' digunakan untuk menunjukkan dua perkara yang bertentangan sifatnya.', 'standard', array['tatabahasa', 'ayat_majmuk', 'kata_hubung']),
('t4', 3, 'Tatabahasa - Ayat Tunggal dan Majmuk', 'Fahami ayat majmuk ini: "Aiman menyanyi sambil memetik gitar di atas pentas." Apakah dua ayat tunggal yang membentuk ayat majmuk di atas?', 'mcq', array['A. Aiman menyanyi. Gitar dipetik di atas pentas.', 'B. Aiman menyanyi di atas pentas. Aiman memetik gitar di atas pentas.', 'C. Aiman menyanyi. Aiman bermain gitar.', 'D. Aiman menyanyi lagu. Aiman membeli gitar.'], 'B', 'Ayat majmuk gabungan tersebut dibentuk daripada dua ayat tunggal yang berkongsi subjek (''Aiman'') dan keterangan tempat (''di atas pentas'').', 'kbat', array['tatabahasa', 'ayat_majmuk', 'analisis_ayat']),
('t4', 3, 'Tatabahasa - Ayat Tunggal dan Majmuk', 'Apakah jenis ayat bagi ayat berikut: "Adik menangis kerana kakinya terluka."', 'mcq', array['A. Ayat tunggal', 'B. Ayat tanya', 'C. Ayat majmuk', 'D. Ayat seruan'], 'C', 'Ayat ini merupakan ayat majmuk kerana terdiri daripada dua klausa yang digabungkan menggunakan kata hubung pancangan ''kerana''.', 'easy', array['tatabahasa', 'ayat_majmuk']),
('t4', 3, 'Tatabahasa - Ayat Tunggal dan Majmuk', 'Ayat majmuk boleh dibentuk dengan menggabungkan tiga atau lebih ayat tunggal menggunakan kata hubung yang sesuai.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Ayat majmuk boleh terdiri daripada gabungan beberapa ayat tunggal dengan menggunakan satu atau lebih kata hubung untuk menyambungkannya.', 'standard', array['tatabahasa', 'ayat_majmuk']),
('t4', 3, 'Tatabahasa - Ayat Tunggal dan Majmuk', 'Gabungkan dua ayat tunggal berikut menggunakan kata hubung yang sesuai: "Fatimah rajin belajar." "Fatimah mendapat keputusan yang cemerlang."', 'fill_blank', null, 'sehingga', 'Kata hubung ''sehingga'' digunakan untuk menerangkan akibat atau kesan daripada sikap Fatimah yang rajin belajar.', 'easy', array['tatabahasa', 'ayat_majmuk', 'kata_hubung']);

-- Topic 4: Karangan - Membina Perenggan dan Menyusun Ayat
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Pilih susunan ayat yang betul untuk membentuk satu perenggan pendahuluan karangan bertajuk "Faedah Membaca Buku": \n(I) Buku ialah jambatan ilmu. \n(II) Oleh itu, kita mestilah rajin membaca pada setiap hari. \n(III) Membaca buku memberikan banyak pengetahuan kepada kita.', 'mcq', array['A. I, II, III', 'B. I, III, II', 'C. III, I, II', 'D. II, I, III'], 'B', 'Susunan bermula dengan penyataan umum (I), diikuti dengan penjelasan (III), dan kesimpulan kecil atau cadangan (II).', 'easy', array['karangan', 'menyusun_ayat', 'perenggan_pendahuluan']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Apakah penanda wacana yang sesuai digunakan untuk memulakan perenggan isi yang kedua dalam sebuah karangan?', 'mcq', array['A. Pada pendapat saya', 'B. Selain itu', 'C. Akhir sekali', 'D. Pada masa yang sama'], 'B', 'Penanda wacana ''Selain itu'' sangat sesuai digunakan untuk menambah isi baharu dalam perenggan seterusnya.', 'standard', array['karangan', 'penanda_wacana', 'membina_perenggan']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', '"Sukan dapat menyihatkan tubuh badan kita. Apabila kita bersukan, badan kita akan berpeluh. Peluh yang keluar ini akan menyingkirkan toksin dalam badan." Apakah isi utama bagi perenggan di atas?', 'mcq', array['A. Peluh menyingkirkan toksin dari badan.', 'B. Sukan dapat menyihatkan tubuh badan.', 'C. Kita perlu bersukan pada setiap petang.', 'D. Badan manusia menghasilkan peluh yang banyak.'], 'B', 'Ayat pertama ialah ayat topik yang menyatakan idea utama iaitu sukan dapat menyihatkan tubuh badan, manakala ayat seterusnya ialah huraian.', 'kbat', array['karangan', 'idea_utama', 'pemahaman_perenggan']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Susun ayat-ayat di bawah supaya menjadi sebuah cerita yang logik tentang berkelah di pantai. \n(P) Kami menolong ibu menghidangkan makanan di atas tikar. \n(Q) Selepas kenyang, kami bermain pasir di tepi pantai. \n(R) Sebaik sahaja tiba di pantai, kami mencari tempat yang redup.', 'mcq', array['A. P, Q, R', 'B. R, P, Q', 'C. R, Q, P', 'D. Q, R, P'], 'B', 'Urutan aktiviti bermula dengan mencari tempat (R), diikuti dengan makan (P), dan kemudian bermain (Q).', 'easy', array['karangan', 'menyusun_ayat', 'penceritaan']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Pilih ayat tanya yang paling sesuai untuk mendapatkan maklumat bagi menulis karangan autobiografi "Aku Sebatang Pensel".', 'mcq', array['A. Di manakah aku dilahirkan?', 'B. Bagaimanakah cara untuk menggunakan pensel?', 'C. Mengapakah murid-murid suka menulis?', 'D. Berapakah harga pensel di kedai buku?'], 'A', 'Karangan autobiografi menceritakan latar belakang diri (asal-usul benda), jadi pertanyaan "Di manakah aku dilahirkan?" membantu memulakan perenggan pendahuluan.', 'standard', array['karangan', 'autobiografi', 'membina_ayat']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Semasa menulis perenggan penutup karangan jenis syarahan, apakah perkara utama yang perlu dimasukkan oleh seorang penulis?', 'mcq', array['A. Mengucapkan terima kasih dan memohon maaf sebelum mengundur diri.', 'B. Memperkenalkan tajuk syarahan kepada penonton.', 'C. Memberikan huraian panjang tentang kebaikan bersukan.', 'D. Menulis pantun jenaka untuk menghiburkan hakim.'], 'A', 'Perenggan penutup syarahan wajib diakhiri dengan permohonan maaf atas sebarang kesilapan dan ucapan terima kasih kepada penonton.', 'standard', array['karangan', 'format_karangan', 'syarahan']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', '"Hari Ahad yang lalu, kami sekeluarga bergotong-royong membersihkan rumah. Ayah mengecat dinding luar. Ibu menyapu sampah. Saya pula __________." Pilih huraian perbuatan yang paling sesuai untuk melengkapkan draf isi karangan tersebut.', 'mcq', array['A. menonton televisyen di ruang tamu', 'B. menyiram pokok bunga di halaman rumah', 'C. pergi bermain basikal bersama kawan', 'D. tidur dengan lena di dalam bilik'], 'B', 'Menyiram pokok bunga ialah tugas pembersihan/pengemasan rumah yang sesuai dengan aktiviti gotong-royong keluarga, manakala pilihan lain bukan tugas gotong-royong.', 'kbat', array['karangan', 'membina_perenggan', 'logik_cerita']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Sebuah karangan yang baik untuk murid Tahun 4 perlu mempunyai sekurang-kurangnya tiga bahagian utama iaitu pendahuluan, isi-isi penting, and penutup.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Struktur karangan standard bahasa Melayu sekolah rendah terdiri daripada tiga komponen wajib iaitu pendahuluan, perenggan isi, dan penutup.', 'easy', array['karangan', 'struktur_karangan']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Ayat topik ialah ayat yang berfungsi untuk menghuraikan secara terperinci contoh-contoh bagi isi perenggan.', 'true_false', array['Betul', 'Salah'], 'Salah', 'Ayat topik ialah ayat yang menyatakan idea atau tema utama perenggan tersebut. Ayat yang menghuraikan contoh ialah ayat contoh atau ayat huraian.', 'standard', array['karangan', 'membina_perenggan', 'struktur_perenggan']),
('t4', 4, 'Karangan - Membina Perenggan dan Menyusun Ayat', 'Susun perkataan-perkataan berikut untuk membentuk ayat yang gramatis: "sekolah / murid-murid / membersihkan / kawasan / bergotong-royong / untuk"', 'fill_blank', null, 'Murid-murid bergotong-royong untuk membersihkan kawasan sekolah.', 'Struktur ayat penyata aktif transitif bermula dengan subjek (Murid-murid) diikuti kata kerja (bergotong-royong) dan penerangan tujuan (untuk membersihkan kawasan sekolah).', 'easy', array['karangan', 'membina_ayat', 'menyusun_perkataan']);

-- Topic 5: Karangan - Format Karangan dan Penulisan Kreatif
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Apakah format yang wajib ada pada bahagian permulaan sebuah karangan laporan?', 'mcq', array['A. Alamat pengirim dan penerima', 'B. Tajuk laporan dengan huruf besar pada setiap awal kata', 'C. Tarikh hari ini di sebelah kanan surat', 'D. Tandatangan penulis di bahagian atas laporan'], 'B', 'Karangan laporan memerlukan tajuk laporan yang jelas ditulis di bahagian atas/tengah halaman.', 'easy', array['karangan', 'format_karangan', 'laporan']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Dalam menulis surat kiriman rasmi, bagaimanakah cara penulisan tarikh yang betul mengikut format tatabahasa bahasa Melayu?', 'mcq', array['A. 21/06/2026', 'B. 21 JUN 2026', 'C. 21 Jun 2026.', 'D. 21 Jun 2026'], 'D', 'Format tarikh surat rasmi ditulis dengan nama bulan bermula huruf besar dan tiada tanda noktah di hujungnya (contoh: 21 Jun 2026).', 'standard', array['karangan', 'format_karangan', 'surat_rasmi']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Anda ingin menulis karangan tentang cara-cara membalas jasa ibu bapa. Antara isi berikut, yang manakah paling utama dan bertepatan dengan peranan seorang anak yang masih bersekolah?', 'mcq', array['A. Membelikan ibu bapa sebuah kereta mewah yang baharu.', 'B. Belajar bersungguh-sungguh dan menghormati mereka pada setiap masa.', 'C. Memberikan wang belanja bulanan yang banyak hasil daripada bekerja sambilan.', 'D. Membawa mereka melancong ke luar negara setiap bulan.'], 'B', 'Bagi murid Tahun 4 (kanak-kanak sekolah), tanggungjawab utama yang praktikal untuk membalas jasa ibu bapa ialah belajar dengan tekun dan menjaga adab sopan.', 'kbat', array['karangan', 'huraian_isi', 'KBAT']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Apakah kata sapaan atau panggilan hormat yang sesuai digunakan untuk menulis surat kiriman tidak rasmi kepada seorang sahabat?', 'mcq', array['A. Menghadap Yang Berhormat Tan Sri', 'B. Ke hadapan sahabatku yang berada di Kuala Lumpur', 'C. Tuan Guru Besar yang dihormati', 'D. Rujukan tuan bertarikh semalam'], 'B', 'Surat kiriman tidak rasmi kepada rakan menggunakan kata sapaan mesra seperti ''Ke hadapan sahabatku''.', 'easy', array['karangan', 'format_karangan', 'surat_tidak_rasmi']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Pilihlah penutup yang paling sesuai untuk karangan catatan harian perkhemahan pengakap sekolah.', 'mcq', array['A. Kami bersurai setelah penat bermain di pusat membeli-belah berhampiran.', 'B. Kami pulang ke rumah dengan gembira walaupun berasa letih kerana mendapat banyak pengalaman berharga.', 'C. Sila pastikan khemah dilipat dengan kemas sebelum anda pulang.', 'D. Pada waktu petang, kami mandi-manda di sungai dengan gembiranya.'], 'B', 'Penutup catatan perkhemahan yang baik menceritakan perasaan gembira/letih semasa pulang dan nilai/pengalaman yang diperoleh.', 'standard', array['karangan', 'catatan_harian', 'penutup_karangan']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Karangan jenis berita mestilah bermula dengan nama tempat ditulis dengan huruf besar sepenuhnya, diikuti dengan tanda koma dan tarikh sebelum perenggan pertama bermula.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Format penulisan berita bahasa Melayu memerlukan pengepala kepala berita seperti "KUALA LUMPUR, 21 Jun -" di awal perenggan pertama.', 'easy', array['karangan', 'format_karangan', 'berita']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Antara berikut, yang manakah merupakan peraturan penting semasa menulis surat kiriman tidak rasmi untuk peperiksaan sekolah?', 'mcq', array['A. Boleh menggunakan singkatan ejaan seperti ''yg'' dan ''dgn''', 'B. Mesti menggunakan bahasa Melayu baku dan ejaan yang penuh', 'C. Boleh menggunakan bahasa rojak agar kelihatan mesra', 'D. Tiada had dan format khusus yang perlu dipatuhi'], 'B', 'Walaupun surat tidak rasmi bersifat santai, ejaan penuh dan bahasa baku tetap diwajibkan dalam penulisan karangan formal sekolah.', 'standard', array['karangan', 'surat_tidak_rasmi', 'tatabahasa']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Dalam karangan jenis dialog, nama watak yang bercakap mestilah ditulis di sebelah kiri, diikuti oleh tanda baca __________ sebelum kata-kata watak tersebut ditulis.', 'fill_blank', null, 'titik bertindih', 'Tanda baca titik bertindih (:) digunakan selepas nama watak dalam format penulisan dialog.', 'standard', array['karangan', 'format_karangan', 'dialog', 'tanda_baca']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Karangan yang menceritakan pengalaman sendiri menyertai rombongan ke Melaka Bandaraya Bersejarah tergolong dalam jenis karangan __________.', 'fill_blank', null, 'keperihalan', 'Karangan keperihalan atau gambaran ialah karangan yang menceritakan peristiwa, lawatan, atau pengalaman sebenar yang dialami.', 'easy', array['karangan', 'jenis_karangan', 'keperihalan']),
('t4', 5, 'Karangan - Format Karangan dan Penulisan Kreatif', 'Apabila menulis karangan cerita tentang membantu mangsa banjir, kita boleh memasukkan nilai murni seperti "bantu-membantu" dan "keprihatinan" untuk menjadikan cerita tersebut lebih menarik dan bermoral.', 'true_false', array['Betul', 'Salah'], 'Betul', 'Memasukkan nilai-nilai murni dan teladan yang baik dapat meningkatkan mutu pengajaran dalam karangan naratif.', 'kbat', array['karangan', 'naratif', 'nilai_murni']);

-- ==========================================================
-- TINGKATAN 3 / PT3 (Dhiya): Tatabahasa, Karangan
-- ==========================================================

-- Topic 1: Tatabahasa
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('f3', 1, 'Tatabahasa', 'Pilih ayat pasif yang betul bagi ayat aktif: "Saya telah membaca buku sejarah itu semalam."', 'mcq', array['Buku sejarah itu telah dibaca oleh saya semalam.', 'Buku sejarah itu telah saya baca semalam.', 'Buku sejarah itu saya telah membaca semalam.', 'Buku sejarah itu telah dibaca semalam oleh saya.'], 'Buku sejarah itu telah saya baca semalam.', 'Bagi kata ganti nama diri pertama (saya, aku, kami, kita), bentuk pasif tidak boleh menggunakan kata kerja berimbuhan ''di-'' dan sendi nama ''oleh''. Kata ganti nama diri pertama mesti mendahului kata kerja dasar yang telah digugurkan imbuhan aktifnya.', 'standard', array['tatabahasa', 'sintaksis']),
('f3', 1, 'Tatabahasa', 'Pilih ayat pasif yang betul bagi ayat aktif: "Kamu mesti menyiapkan tugasan itu sebelum hari esok."', 'mcq', array['Tugasan itu mesti disiapkan oleh kamu sebelum hari esok.', 'Tugasan itu mesti kamu siapkan sebelum hari esok.', 'Tugasan itu kamu mesti siapkan sebelum hari esok.', 'Tugasan itu disiapkan oleh kamu mesti sebelum hari esok.'], 'Tugasan itu mesti kamu siapkan sebelum hari esok.', 'Bagi kata ganti nama diri kedua (kamu, anda, awak), ayat pasif dibentuk dengan meletakkan kata ganti nama diri kedua sebelum kata kerja dasar tanpa imbuhan ''di-'' dan ''oleh''.', 'standard', array['tatabahasa', 'sintaksis']),
('f3', 1, 'Tatabahasa', 'Pilih ayat pasif yang betul bagi ayat aktif: "Encik Ali memandu kereta baharu itu ke pejabat."', 'mcq', array['Kereta baharu itu dipandu oleh Encik Ali ke pejabat.', 'Kereta baharu itu Encik Ali pandu ke pejabat.', 'Kereta baharu itu dipandu ke pejabat oleh beliau.', 'Kereta baharu itu memandu oleh Encik Ali ke pejabat.'], 'Kereta baharu itu dipandu oleh Encik Ali ke pejabat.', 'Bagi kata ganti nama diri ketiga (dia, mereka, beliau) atau nama khas/am (Encik Ali), ayat pasif dibentuk dengan kata kerja berawalan ''di-'' dan diikuti oleh kata sendi ''oleh''.', 'easy', array['tatabahasa', 'sintaksis']),
('f3', 1, 'Tatabahasa', 'Kenal pasti ayat pasif yang salah tatabahasanya.', 'mcq', array['Surat kiriman rasmi itu telah kami hantar kepada pihak penganjur.', 'Segala nasihat ibu akan saya ingat sampai bila-bila.', 'Kuih-muih yang lazat itu telah dihidangkan oleh kami kepada para tetamu.', 'Tugasan yang rumit itu dapat diselesaikan oleh mereka dalam masa sejam.'], 'Kuih-muih yang lazat itu telah dihidangkan oleh kami kepada para tetamu.', 'Ayat ini salah kerana menggunakan formula ''dihidangkan oleh kami'' (kata ganti nama diri pertama pasif menggunakan di- dan oleh). Sepatutnya ialah ''Kuih-muih yang lazat itu telah kami hidangkan kepada para tetamu.''', 'kbat', array['tatabahasa', 'sintaksis']),
('f3', 1, 'Tatabahasa', 'Pilih cakap pindah yang betul bagi cakap ajuk berikut:
"Saya tidak dapat hadir ke sekolah hari ini kerana demam," kata Ahmad kepada gurunya.', 'mcq', array['Ahmad memberitahu gurunya bahawa saya tidak dapat hadir ke sekolah hari ini kerana demam.', 'Ahmad memberitahu gurunya bahawa dia tidak dapat hadir ke sekolah pada hari itu kerana demam.', 'Ahmad berkata kepada gurunya bahawa beliau tidak dapat hadir ke sekolah hari itu kerana demam.', 'Ahmad memberitahu gurunya jangan hadir ke sekolah pada hari itu kerana demam.'], 'Ahmad memberitahu gurunya bahawa dia tidak dapat hadir ke sekolah pada hari itu kerana demam.', 'Dalam penukaran cakap ajuk kepada cakap pindah, kata ganti diri ''saya'' bertukar menjadi ''dia'', dan penunjuk masa ''hari ini'' bertukar menjadi ''hari itu'' atau ''pada hari tersebut''.', 'standard', array['tatabahasa', 'sintaksis', 'wacana']),
('f3', 1, 'Tatabahasa', 'Pilih cakap pindah yang betul bagi cakap ajuk berikut:
"Mengapakah kamu termenung di sini, Siti?" tanya Aminah.', 'mcq', array['Aminah bertanya kepada Siti sebab dia termenung di situ.', 'Aminah bertanya kepada Siti mengapa kamu termenung di sini.', 'Aminah menanyakan Siti bahawa dia termenung di sana pada masa itu.', 'Aminah meminta Siti supaya tidak termenung di situ lagi.'], 'Aminah bertanya kepada Siti sebab dia termenung di situ.', 'Penukaran cakap ajuk jenis pertanyaan memerlukan kata kerja pelapor ''bertanya'' atau ''ingin tahu''. Kata ganti diri ''kamu'' berubah menjadi ''dia'', penunjuk tempat ''di sini'' berubah menjadi ''di situ'', dan kata tanya ''mengapa'' boleh diganti dengan ''sebab''.', 'standard', array['tatabahasa', 'sintaksis', 'wacana']),
('f3', 1, 'Tatabahasa', 'Pilih cakap pindah yang betul bagi cakap ajuk berikut:
"Jangan buang sampah di kawasan ini," kata pengawal keselamatan kepada pemuda itu.', 'mcq', array['Pengawal keselamatan menyuruh pemuda itu jangan buang sampah di kawasan ini.', 'Pengawal keselamatan melarang pemuda itu membuang sampah di kawasan tersebut.', 'Pengawal keselamatan berkata kepada pemuda itu jangan membuang sampah di kawasan ini.', 'Pengawal keselamatan meminta pemuda itu tidak membuang sampah di kawasan ini.'], 'Pengawal keselamatan melarang pemuda itu membuang sampah di kawasan tersebut.', 'Ayat larangan yang menggunakan kata ''jangan'' ditukarkan menjadi cakap pindah dengan menggunakan kata kerja pelapor ''melarang'' atau ''menegah''. Kata tunjuk ''ini'' pula berubah menjadi ''itu'' atau ''tersebut''.', 'standard', array['tatabahasa', 'sintaksis', 'wacana']),
('f3', 1, 'Tatabahasa', 'Tukarkan cakap ajuk berikut kepada cakap pindah yang paling tepat:
"Syabas, kamu telah berjaya mendapat tempat pertama dalam pertandingan itu!" kata guru besar kepada murid-muridnya.', 'mcq', array['Guru besar mengucapkan syabas kepada murid-muridnya kerana mereka telah berjaya mendapat tempat pertama dalam pertandingan itu.', 'Guru besar mengucapkan tahniah kepada murid-muridnya serta menyatakan bahawa mereka telah berjaya mendapat tempat pertama dalam pertandingan tersebut.', 'Guru besar menasihati murid-muridnya supaya mendapat tempat pertama dalam pertandingan itu.', 'Guru besar memberitahu murid-muridnya bahawa dia telah berjaya mendapat tempat pertama dalam pertandingan tersebut.'], 'Guru besar mengucapkan tahniah kepada murid-muridnya serta menyatakan bahawa mereka telah berjaya mendapat tempat pertama dalam pertandingan tersebut.', 'Kata seru ''syabas'' dalam cakap ajuk diterjemahkan sebagai tindakan ''mengucapkan tahniah'' dalam cakap pindah. Kata ganti diri ''kamu'' (jamak) bertukar menjadi ''mereka'', dan kata tunjuk ''itu'' bertukar menjadi ''tersebut''.', 'kbat', array['tatabahasa', 'sintaksis', 'wacana']),
('f3', 1, 'Tatabahasa', 'Pilih ayat yang menggunakan kata pemeri dengan betul.', 'mcq', array['Matlamat utama kempen keselamatan jalan raya itu ialah untuk mengurangkan kadar kemalangan.', 'Keputusan yang diambil oleh pihak pengurusan syarikat adalah adil dan saksama.', 'Hobi kegemaran kakak saya pada waktu lapang adalah membaca novel fiksyen.', 'Sumbangan derma yang dikumpulkan itu ialah untuk mangsa banjir di Pantai Timur.'], 'Keputusan yang diambil oleh pihak pengurusan syarikat adalah adil dan saksama.', 'Kata pemeri ''ialah'' digunakan sebelum Frasa Nama. Kata pemeri ''adalah'' digunakan sebelum Frasa Adjektif (adil dan saksama) dan Frasa Sendi Nama (untuk...). Dalam pilihan lain, ''ialah'' digunakan sebelum Frasa Sendi Nama dan ''adalah'' sebelum Frasa Kerja.', 'standard', array['tatabahasa']),
('f3', 1, 'Tatabahasa', 'Pilih ayat yang tidak mempunyai sebarang kesalahan ejaan atau imbuhan.', 'mcq', array['Kebanyakkan murid sekolah itu menyertai aktiviti kokurikulum pada hari Sabtu.', 'Cadangan untuk memperkasakan ekonomi luar bandar telah diperoleh daripada mesyuarat semalam.', 'Kita tidak sepatutnya mengenepikan pandangan orang tua dalam membuat keputusan keluarga.', 'Pihak sekolah sedang mengenalpasti murid-murid yang memerlukan bantuan komputer riba.'], 'Cadangan untuk memperkasakan ekonomi luar bandar telah diperoleh daripada mesyuarat semalam.', 'Ejaan ''kebanyakan'' sepatutnya satu ''k''. Imbuhan ''mengenepikan'' sepatutnya ''mengetepikan''. Frasa ''mengenalpasti'' sepatutnya dieja jarak sebagai ''mengenal pasti'' kerana ia kata majmuk tidak mantap yang menerima imbuhan awalan sahaja.', 'standard', array['tatabahasa']),
('f3', 1, 'Tatabahasa', 'Pilih ayat yang menggunakan kata sendi nama dengan betul.', 'mcq', array['Perkongsian ilmu itu sangat bermanfaat bagi murid-murid terutamanya di kalangan remaja.', 'Bapa menerima sepucuk surat daripada rakannya yang berada di Australia.', 'Ibu menghadiahi seutas jam tangan kepada adik sempena hari lahirnya.', 'Para pelancong itu datang dari pelbagai negara untuk melihat keindahan Malaysia.'], 'Bapa menerima sepucuk surat daripada rakannya yang berada di Australia.', '''Daripada'' digunakan untuk orang, asal-usul, keanggotaan, perbandingan, dan sumber (KABO). Rakannya ialah manusia/orang, maka kata sendi yang betul ialah ''daripada''. Penggunaan ''di kalangan'' sepatutnya ''dalam kalangan''. ''Menghadiahi'' sepatutnya diikuti objek bernyawa langsung (e.g. menghadiahi adik seutas...).', 'standard', array['tatabahasa']),
('f3', 1, 'Tatabahasa', 'Pilih ayat yang betul dari segi tatabahasa.', 'mcq', array['Para guru-guru sedang bermesyuarat di bilik persidangan utama.', 'Kedua buah sekolah itu telah terpilih sebagai sekolah contoh di daerah ini.', 'Semua murid-murid dikehendaki berkumpul di tapak perhimpunan sekarang.', 'Kebanyakan remaja hari ini gemar melayari media sosial untuk mencari maklumat.'], 'Kebanyakan remaja hari ini gemar melayari media sosial untuk mencari maklumat.', 'Pilihan A lewah kerana menggabungkan penanda jamak ''para'' dengan kata ganda ''guru-guru''. Pilihan B sepatutnya ''kedua-dua buah''. Pilihan C lewah kerana menggabungkan ''semua'' dengan ''murid-murid''.', 'easy', array['tatabahasa']),
('f3', 1, 'Tatabahasa', 'Pilih peribahasa yang paling sesuai bagi situasi di bawah:

Syamil rajin belajar dan tidak pernah berputus asa walaupun menghadapi pelbagai kesukaran demi mencapai cita-citanya untuk menjadi seorang doktor.', 'mcq', array['Ukur baju di badan sendiri.', 'Bagai aur dengan tebing.', 'Kalau tidak dipecahkan ruyung, manakan dapat sagunya.', 'Genggam bara api biar sampai jadi arang.'], 'Kalau tidak dipecahkan ruyung, manakan dapat sagunya.', 'Peribahasa ''Kalau tidak dipecahkan ruyung, manakan dapat sagunya'' bermaksud cita-cita atau hasil yang baik tidak akan diperoleh tanpa usaha yang gigih dan tekun.', 'standard', array['peribahasa']),
('f3', 1, 'Tatabahasa', 'Masyarakat di Kampung Seri Murni sentiasa bekerjasama dan bantu-membantu dalam menguruskan majlis perkahwinan penduduk kampung. Sikap mereka ini bagai...', 'mcq', array['melepaskan batuk di tangga.', 'aur dengan tebing.', 'menatang minyak yang penuh.', 'mencurah air ke daun keladi.'], 'aur dengan tebing.', 'Peribahasa ''bagai aur dengan tebing'' bermaksud hubungan atau sikap tolong-menolong dan bekerjasama erat dalam kalangan masyarakat.', 'easy', array['peribahasa']),
('f3', 1, 'Tatabahasa', 'Walaupun Haziq telah melakukan pelbagai kesilapan lampau yang mengecewakan keluarganya, bapanya tetap memaafkan dan menerimanya kembali dengan tangan terbuka kerana sedar bahawa hubungan kekeluargaan tidak boleh diputuskan begitu sahaja.

Apakah peribahasa yang paling tepat bagi menggambarkan situasi ini?', 'mcq', array['Bapa borek, anak rintik.', 'Air dicencang tidak akan putus.', 'Sesal dahulu pendapatan, sesal kemudian tidak berguna.', 'Alang-alang menyeluk pekasam, biar sampai ke pangkal lengan.'], 'Air dicencang tidak akan putus.', 'Peribahasa ''Air dicencang tidak akan putus'' melambangkan hubungan kekeluargaan yang erat dan tidak akan terputus walaupun berlaku perselisihan faham.', 'kbat', array['peribahasa']),
('f3', 1, 'Tatabahasa', 'Adakah ayat pasif berikut betul dari segi tatabahasa?

"Buku latihan itu dibaca oleh saya di perpustakaan petang semalam."', 'true_false', null, 'Salah', 'Bagi kata ganti nama diri pertama (saya), ayat pasif yang betul ialah ''Buku latihan itu saya baca...''. Struktur ''dibaca oleh saya'' adalah salah tatabahasa.', 'standard', array['tatabahasa', 'sintaksis']),
('f3', 1, 'Tatabahasa', 'Adakah penukaran cakap ajuk kepada cakap pindah di bawah betul?

Cakap Ajuk: "Saya akan menghantar kerja sekolah ini esok," kata Danish.
Cakap Pindah: Danish berkata bahawa dia akan menghantar kerja sekolah itu pada keesokan harinya.', 'true_false', null, 'Betul', 'Penukaran ini betul kerana ''saya'' berubah menjadi ''dia'', ''ini'' berubah menjadi ''itu'', and ''esok'' berubah menjadi ''pada keesokan harinya'' secara konsisten.', 'standard', array['tatabahasa', 'sintaksis', 'wacana']),
('f3', 1, 'Tatabahasa', 'Perkataan "diperolehi" ialah ejaan dan bentuk imbuhan pasif yang betul mengikut sistem ejaan Rumi bahasa Melayu baharu.', 'true_false', null, 'Salah', 'Bentuk ejaan yang betul mengikut tatabahasa ialah ''diperoleh'' tanpa akhiran ''-i''.', 'easy', array['tatabahasa']),
('f3', 1, 'Tatabahasa', 'Lengkapkan ayat berikut dengan memilih kata pemeri yang paling sesuai:

Tujuan utama lawatan sambil belajar ke Petrosains itu ________ untuk memberikan pendedahan sains praktikal kepada murid-murid.', 'fill_blank', null, 'adalah', 'Kata pemeri ''adalah'' digunakan sebelum Frasa Sendi Nama (''untuk memberikan...'').', 'standard', array['tatabahasa']),
('f3', 1, 'Tatabahasa', 'Lengkapkan ayat berikut dengan kata sendi nama yang betul:

Kita perlulah memupuk nilai-nilai murni dan sikap toleransi ________ kalangan masyarakat berbilang kaum di negara ini.', 'fill_blank', null, 'dalam', 'Penggunaan yang betul mengikut standard bahasa Melayu ialah ''dalam kalangan'', bukannya ''di kalangan''.', 'easy', array['tatabahasa']);

-- Topic 2: Karangan
insert into bm_questions (level, topic, topic_title, question_text, question_type, options, correct_answer, explanation, difficulty, tags) values
('f3', 2, 'Karangan', 'Berapakah jumlah patah perkataan yang ditetapkan bagi penulisan Karangan Pendek (Bahagian A) dalam peperiksaan UASA Kertas 2?', 'mcq', array['30 hingga 50 patah perkataan.', '50 hingga 80 patah perkataan.', '80 hingga 120 patah perkataan.', 'Tidak kurang daripada 180 patah perkataan.'], '50 hingga 80 patah perkataan.', 'Mengikut format rasmi UASA Kertas 2 Bahagian A, murid dikehendaki menulis karangan pendek yang panjangnya antara 50 hingga 80 patah perkataan.', 'easy', array['karangan_pendek']),
('f3', 2, 'Karangan', 'Apakah aspek yang paling penting ketika menulis Karangan Pendek berdasarkan bahan grafik?', 'mcq', array['Menulis huraian yang sangat panjang sehingga melebihi 150 perkataan.', 'Memasukkan semua kata kunci atau frasa rangsangan yang diberikan dalam soalan.', 'Menggunakan format surat kiriman rasmi.', 'Mengabaikan gambar dan hanya menulis idea sendiri.'], 'Memasukkan semua kata kunci atau frasa rangsangan yang diberikan dalam soalan.', 'Calon wajib menyepadukan semua frasa atau kata kunci rangsangan yang disediakan ke dalam perenggan karangan pendek untuk mendapat markah penuh bagi aspek isi.', 'standard', array['karangan_pendek']),
('f3', 2, 'Karangan', 'Mengikut Formula Karangan 5 Perenggan (Blueprint Karangan), bagaimanakah pembahagian perenggan yang paling seimbang?', 'mcq', array['1 perenggan pendahuluan, 3 perenggan isi, 1 perenggan penutup.', '1 perenggan pendahuluan, 2 perenggan isi, 2 perenggan penutup.', '2 perenggan pendahuluan, 2 perenggan isi, 1 perenggan penutup.', '5 perenggan yang semuanya mengandungi isi tanpa pendahuluan dan penutup.'], '1 perenggan pendahuluan, 3 perenggan isi, 1 perenggan penutup.', 'Formula Karangan 5 Perenggan membahagikan karangan secara sistematik kepada 1 perenggan pendahuluan, 3 perenggan isi utama, dan 1 perenggan penutup.', 'easy', array['wacana']),
('f3', 2, 'Karangan', 'Dalam "Formula Mudah 6 Ayat" untuk membina perenggan isi, apakah fungsi bagi Ayat 1 (Pendapat)?', 'mcq', array['Menyatakan contoh konkrit bagi isi.', 'Menyatakan pendirian awal atau tajuk kecil perenggan isi tersebut.', 'Menerangkan impak atau kesan jangka panjang isi.', 'Merumuskan keseluruhan isi perenggan.'], 'Menyatakan pendirian awal atau tajuk kecil perenggan isi tersebut.', 'Ayat 1 (Pendapat - P) berfungsi sebagai ayat topik yang memperkenalkan isi atau cadangan utama yang akan dibincangkan dalam perenggan tersebut.', 'standard', array['wacana']),
('f3', 2, 'Karangan', 'Manakah antara penanda wacana berikut yang paling sesuai digunakan untuk memulakan Ayat 3 (Huraian - H) dalam perenggan isi?', 'mcq', array['Sebagai tamsilnya,...', 'Hal ini dikatakan demikian kerana...', 'Impaknya,...', 'Oleh itu, jelaslah bahawa...'], 'Hal ini dikatakan demikian kerana...', 'Penanda wacana ''Hal ini dikatakan demikian kerana...'' digunakan untuk memberikan penjelasan mendalam atau huraian sebab dan akibat bagi menyokong isi.', 'easy', array['wacana']),
('f3', 2, 'Karangan', 'Apakah peranan utama Ayat 4 (Isi & Contoh - IC) dalam struktur penulisan perenggan isi karangan?', 'mcq', array['Mengulang semula isi utama untuk kali ketiga.', 'Mengemukakan bukti konkrit atau contoh realistik bagi menyokong hujah.', 'Memberikan cadangan baharu yang berbeza daripada isi utama.', 'Menyimpulkan keseluruhan karangan.'], 'Mengemukakan bukti konkrit atau contoh realistik bagi menyokong hujah.', 'Ayat 4 (IC) bertujuan memperkukuh hujah dengan membekalkan contoh konkrit yang sahih, praktikal, dan mudah difahami pembaca.', 'standard', array['wacana']),
('f3', 2, 'Karangan', 'Pilih ayat yang paling tepat menggambarkan "Kesan (K)" dalam perenggan isi bertemakan Langkah Mengurangkan Pencemaran Sungai.', 'mcq', array['Kesannya, kualiti air sungai akan meningkat dan ekosistem hidupan akuatik akan terpelihara.', 'Kerajaan perlulah mendenda kilang-kilang yang membuang sisa toksik ke dalam sungai.', 'Sebagai contoh, kempen Cintai Sungai Kita boleh dilaksanakan di seluruh negara.', 'Hal ini dikatakan demikian kerana sampah-sarap menyumbat aliran air sungai.'], 'Kesannya, kualiti air sungai akan meningkat dan ekosistem hidupan akuatik akan terpelihara.', 'Ayat ini menunjukkan kesan langsung (implikasi positif) daripada tindakan yang dicadangkan dalam isi perenggan.', 'standard', array['wacana']),
('f3', 2, 'Karangan', 'Susun semula ayat-ayat di bawah mengikut urutan "Formula Mudah 6 Ayat" (P, I, H, IC, K, PH) yang betul bagi menghasilkan perenggan isi yang koheren.

1. Kesannya, minda remaja akan lebih terbuka untuk menghargai warisan seni negara.
2. Pada pendapat saya, langkah penting untuk memelihara permainan tradisional adalah dengan menganjurkan kelab permainan di sekolah.
3. Sebagai tamsilnya, pihak sekolah boleh mengadakan pertandingan congkak dan gasing sewaktu aktiviti kokurikulum.
4. Hal ini dikatakan demikian kerana generasi muda kini kurang pendedahan terhadap keunikan budaya tempatan.
5. Kelab ini ditubuhkan bagi melatih para murid memahami peraturan dan cara bermain dengan betul.
6. Oleh itu, jelaslah bahawa penubuhan kelab permainan tradisional di sekolah merupakan wadah efektif untuk memelihara warisan bangsa.', 'mcq', array['2 -> 5 -> 4 -> 3 -> 1 -> 6', '2 -> 4 -> 5 -> 3 -> 1 -> 6', '2 -> 5 -> 3 -> 4 -> 1 -> 6', '2 -> 4 -> 3 -> 5 -> 1 -> 6'], '2 -> 5 -> 4 -> 3 -> 1 -> 6', 'Urutan P, I, H, IC, K, PH ialah: P (Ayat 2: Pendapat utama - menganjurkan kelab sekolah), I (Ayat 5: Isi tujuan - melatih murid memahami peraturan), H (Ayat 4: Huraian sebab - generasi muda kurang pendedahan), IC (Ayat 3: Contoh - pertandingan congkak dan gasing), K (Ayat 1: Kesan - minda remaja terbuka menghargai warisan), PH (Ayat 6: Penutup perenggan - penegasan semula isi).', 'kbat', array['wacana']),
('f3', 2, 'Karangan', 'Apakah ciri format yang wajib ada dalam penulisan Surat Kiriman Rasmi?', 'mcq', array['Menggunakan kata aluan syarahan seperti "Tuan Pengerusi Majlis".', 'Menyertakan tandatangan penulis dan jawatan di sebelah bawah kiri surat.', 'Memulakan surat dengan bertanya khabar tentang keadaan keluarga penerima.', 'Mengakhiri surat dengan meletakkan tarikh di sebelah atas kanan sahaja tanpa alamat pengirim.'], 'Menyertakan tandatangan penulis dan jawatan di sebelah bawah kiri surat.', 'Surat kiriman rasmi mewajibkan format tandatangan, nama penuh (huruf besar), dan jawatan pengirim di bahagian bawah kiri surat.', 'easy', array['karangan_pendek']),
('f3', 2, 'Karangan', 'Manakah antara ungkapan berikut merupakan penyapaan format (salutation) yang betul bagi memulakan karangan jenis Syarahan?', 'mcq', array['Ke hadapan sahabatku yang berada di Sarawak, apa khabar?', 'Yang Berusaha Tuan Pengetua, barisan hakim yang arif, dan hadirin yang dihormati sekalian.', 'Laporan ini disediakan oleh Setiausaha Kelab Bahasa Melayu.', 'Merujuk kepada perkara di atas, saya ingin membuat aduan tentang masalah kebersihan.'], 'Yang Berusaha Tuan Pengetua, barisan hakim yang arif, dan hadirin yang dihormati sekalian.', 'Karangan syarahan atau ucapan memerlukan kata aluan formal untuk menyapa pengerusi majlis, panel hakim, tetamu kehormat, serta hadirin.', 'easy', array['karangan_pendek']),
('f3', 2, 'Karangan', 'Pilih penanda wacana yang paling sesuai untuk menggabungkan perenggan isi kedua yang membincangkan langkah seterusnya (isi tambahan).', 'mcq', array['Oleh hal yang demikian,...', 'Di samping itu,...', 'Sebagai kesimpulannya,...', 'Tuntasnya,...'], 'Di samping itu,...', '''Di samping itu'' atau ''Selain itu'' digunakan untuk menambah isi atau idea baharu yang selari dengan isi sebelumnya.', 'easy', array['wacana']),
('f3', 2, 'Karangan', 'Apakah elemen penting yang patut terkandung dalam perenggan Penutup (Paragraph 5) karangan panjang?', 'mcq', array['Contoh-contoh baharu yang belum dibincangkan dalam perenggan isi.', 'Rumusan keseluruhan isi, cadangan peranan pihak berkepentingan, dan harapan masa hadapan.', 'Dialog cakap ajuk antara dua orang watak.', 'Alamat dan tarikh laporan disediakan.'], 'Rumusan keseluruhan isi, cadangan peranan pihak berkepentingan, dan harapan masa hadapan.', 'Perenggan penutup berfungsi memberikan kesimpulan kepada hujah, menyatakan peranan pihak-pihak terlibat, serta mengemukakan harapan tentang masa depan isu tersebut.', 'standard', array['wacana']),
('f3', 2, 'Karangan', 'Apakah matlamat utama Ayat 6 (Penutup/Harapan - PH) di akhir setiap perenggan isi?', 'mcq', array['Menarik perhatian pembaca dengan soalan retorik.', 'Menegaskan semula isi utama perenggan tersebut supaya hujah kelihatan kukuh dan tidak tergantung.', 'Memperkenalkan tajuk perenggan isi yang seterusnya.', 'Meminta maaf atas sebarang kesilapan dalam hujah.'], 'Menegaskan semula isi utama perenggan tersebut supaya hujah kelihatan kukuh dan tidak tergantung.', 'Ayat PH berfungsi sebagai penyimpul perenggan isi yang menegaskan semula perkaitan antara isi utama dengan tugasan soalan.', 'standard', array['wacana']),
('f3', 2, 'Karangan', 'Manakah antara susunan format Laporan yang betul di bahagian bawah karangan?', 'mcq', array['Tarikh di sebelah kiri, tandatangan di sebelah kanan.', 'Tandatangan pengarang dan jawatan di sebelah kiri bawah, tarikh laporan di sebelah kanan bawah (bertentangan dengan tandatangan).', 'Nama pengarang diletakkan di bahagian tajuk utama sahaja.', 'Tandatangan diletakkan di bahagian atas laporan sebelum perenggan pertama.'], 'Tandatangan pengarang dan jawatan di sebelah kiri bawah, tarikh laporan di sebelah kanan bawah (bertentangan dengan tandatangan).', 'Format laporan rasmi memerlukan tandatangan penulis laporan berserta nama jawatannya di sebelah kiri bawah, manakala tarikh ditulis di sebelah kanan bawah setentang dengan tandatangan.', 'standard', array['karangan_pendek']),
('f3', 2, 'Karangan', 'Diberi soalan karangan: Bincangkan cara-cara memupuk semangat patriotik dalam kalangan murid sekolah. Antara berikut, manakah penyataan contoh (IC) yang paling kurang sesuai untuk menyokong isi peranan pihak sekolah?', 'mcq', array['Pihak sekolah boleh menganjurkan lawatan sambil belajar ke Muzium Negara semasa cuti sekolah.', 'Guru sejarah boleh menggunakan tayangan video dokumentari perjuangan tokoh kemerdekaan semasa PdPc.', 'Ibu bapa boleh membawa anak-anak melancong ke luar negara bagi menghargai negara sendiri.', 'Pihak sekolah boleh melancarkan sambutan Bulan Kemerdekaan dengan mengadakan pertandingan nyanyian lagu patriotik.'], 'Ibu bapa boleh membawa anak-anak melancong ke luar negara bagi menghargai negara sendiri.', 'Contoh C tidak relevan kerana soalan bertanyakan ''peranan pihak sekolah'', manakala jawapan C memfokuskan kepada tindakan ''ibu bapa''.', 'kbat', array['wacana']),
('f3', 2, 'Karangan', 'Dalam peperiksaan UASA Bahasa Melayu Kertas 2 Bahagian B (Karangan Panjang), panjang karangan hendaklah tidak kurang daripada 180 patah perkataan.', 'true_false', null, 'Betul', 'Ketetapan rasmi UASA Kertas 2 Bahagian B mengehadkan panjang karangan kepada minimum 180 patah perkataan.', 'easy', array['wacana']),
('f3', 2, 'Karangan', 'Penanda wacana "Tuntasnya" paling sesuai digunakan di permulaan Ayat 1 (Ayat Pendapat) dalam perenggan isi kedua.', 'true_false', null, 'Salah', 'Penanda wacana ''Tuntasnya'' bermaksud ''kesimpulannya'' atau ''akhir kata'', oleh itu ia hanya sesuai digunakan untuk memulakan perenggan penutup karangan.', 'standard', array['wacana']),
('f3', 2, 'Karangan', 'Isi perenggan boleh disokong dengan contoh. Lengkapkan ayat contoh di bawah dengan perkataan yang bermaksud "sebagai contoh":

________, pihak sekolah boleh mengadakan kempen kesedaran tentang kebersihan alam sekitar secara berkala.', 'fill_blank', null, 'Sebagai tamsilnya', 'Perkataan ''Sebagai tamsilnya'' merupakan penanda wacana klasik/tinggi yang digunakan untuk memperkenalkan contoh dalam ayat penulisan karangan.', 'standard', array['wacana']),
('f3', 2, 'Karangan', 'Dalam Formula Mudah 6 Ayat, huruf ''K'' merujuk kepada ________, yang menjelaskan kesan atau implikasi daripada tindakan yang dinyatakan dalam isi.', 'fill_blank', null, 'Kesan', 'Dalam formula perenggan (P, I, H, IC, K, PH), huruf ''K'' melambangkan ''Kesan'', iaitu ayat yang menerangkan impak atau kesan jangka panjang/pendek daripada tindakan dan contoh yang diberikan.', 'easy', array['wacana']),
('f3', 2, 'Karangan', 'Karangan jenis syarahan memerlukan murid menulis ungkapan penutup seperti "Sekian, ________" di bahagian akhir karangan sebagai tanda hormat kepada hadirin.', 'fill_blank', null, 'terima kasih', 'Format syarahan, ceramah, dan ucapan mestilah diakhiri dengan ungkapan terima kasih (e.g., ''Sekian, terima kasih'') selepas perenggan penutup.', 'easy', array['karangan_pendek']);

